version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mab
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis_dev:
    image: redis:latest
    ports:
      - '6379:6379'
    command: ['redis-server'] #--save 20 1 --loglevel warning --requirepass
    volumes:
      - ./cache:/data